# permissions for end users to view ecservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecservice-viewer-role
rules:
- apiGroups:
  - kubeec.inspursoft.com
  resources:
  - ecservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeec.inspursoft.com
  resources:
  - ecservices/status
  verbs:
  - get
